os:
    - linux

language: java

jdk:
    - openjdk11

env:
    - GRAALVM_VERSION="19.0.0"

install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
        curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
        tar -xzf graalvm.tar.gz

script:
    - export JAVA_HOME="$(pwd)/graalvm-ce-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
    - mvn clean
    - mvn package
    - mvn exec:exec
    
before_deploy:
    - cd ~
    
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file: "my-app-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
